### PR TITLE
Configure trusted publishing

### PR DESCRIPTION
**Pull request by jaraco**
- [x] Configure project in PyPI for trusted publishing.

### CODE REVIEW

**Review by diogobaeder — APPROVED** [review]
Awesome stuff!

**Comment by jaraco** [comment]
This is my first attempt at configuring a skeleton project for trusted publishing.

I was expecting [based on the docs](https://docs.pypi.org/trusted-publishers/using-a-publisher/) that the diff would be small and straightforward, but it turned out to be complicated.

The existing `release` env in tox had been configured to work both for a GHA release and a manual release, but because the "publish" action depends on the package being built and because the "GitHub release" happens _after_ that, it required splitting the `release` env into two, a `build` and `gh_release` env, both of which have significant overlap with the manual `release`.

What I really want is for the Action to configure the authentication for twine to use.

**Comment by jaraco** [comment]
In this latest change, I've been able to remove the diff from tox.ini altogether. I'm not sure it'll work, but I think it's worth a shot. Along with this change, we need to [configure the project](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) in PyPI to accept this project as the trusted publisher:

- owner: coherent-oss
- repo name: python-kustomize
- workflow: main.yml
- environment: release

**Comment by diogobaeder** [comment]
Awesome, I support you in your attempt, @jaraco ! Let me configure the project now in PyPI then.

**Comment by diogobaeder** [comment]
@jaraco done!

**Pull request merged**
